
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>$if(title)$$pagetitle$ — $endif$</title>

        <link rel="stylesheet" type="text/css" href="/css/style.css" />
        <link rel="icon" href="/images/icon.ico">

        <meta name="keywords" content="science,physics,cosmology" />
        <meta name="description" content="Website." />
    </head>
    <body>
        <div id="main">
            <div id="header">
                <a href="/">
                    <!-- <svg width="50" height="30"><circle cx="20" cy="20" r="10" fill="black" /></svg> -->
                    <img src="/images/sidebar.jpg" alt="" width="50px" style="margin-left: -15px; margin-top: -10px;"/>
                    $if(title)$$pagetitle$$else$$endif$
                </a>
            </div>

            <div id="sidebar">
                <a href="/">home</a>
            </div>

            <div id="content">

                $body$

            </div>

            <div id="footer">
            </div>
        </div>

    </body>

</html>
